### ISSUE TITLE
Provide the Getting-Started-Container through Docker Hub and/or GHCR

### ISSUE THREAD

**Issue by ionicsolutions** [anovos/anovos#36]
I suggest to use GitHub actions push a new version every time it changes.

Then, we can tell users to download the image instead of having to build it themselves.

**Comment by VishnuGowthem** [comment]
@ionicsolutions  we do have one docker hub image that we added as part of the instructions in the README. 

choose to pull the notebook image from our docker hub public repo and run the image:

```bash
sudo docker pull anovos/anovos-notebook-demo:0.1
sudo docker run -p 8888:8888 anovos/anovos-notebook-demo:0.1
```

and open the link to `http://127.0.0.1:8888/?token...` generated by the Jupyter NotebookApp:

We can maybe change the shell script to just pull from docker hub instead of building a new image by the users.

**Comment by ionicsolutions** [comment]
Yes, I saw that 👍🏻 

This issue was more of a reminder to re-organize the demo instructions so that this becomes the default method and set up the Docker build as an Action so that there's always an up-to-date version of the demo image available on Docker Hub.

**Comment by ionicsolutions** [comment]
Adressed by PR #52
