### ISSUE TITLE
Interest to contribut

### ISSUE THREAD

**Issue by ziedbouf** [anovos/anovos#58]
This an interesting initiative and i am looking to contribute,  but few questions i have in mind and i would like to know if these are open interesting in the context of anovos:

1. What do you think of cross engine execution that we can consider spark, ray and dask as main players?
2. For data quality, Apache Griiffin have done interesting work on spark by providing facilities to implement data quality metrics such as timeliness, uniqueness, etc...  This could be achieved through the usage of deequ but that can be tricker if cross engine execution is envisaged
3. for features engineering, what do you of tools like [featuretools](https://featuretools.alteryx.com/en/stable/) from alteryx?

In both cases, the project looks very promising and it will be interested to see how to contribute to anovos.

**Comment by kajanansangar** [comment]
@ziedbouf thank you for joining our contributor list. Great to have you !! Please see my answers inline. 

> This an interesting initiative and i am looking to contribute, but few questions i have in mind and i would like to know if these are open interesting in the context of anovos:
> 
> 1. What do you think of cross engine execution that we can consider spark, ray and dask as main players?

**Anovos has been designed as a comprehensive and scalable feature engineering tool using Apache Spark. Once we achieve that goal we will focus on bringing further support for other distributed data processing platforms like Ray & Dask. But thank you for your pointers.**

> 2. For data quality, Apache Griiffin have done interesting work on spark by providing facilities to implement data quality metrics such as timeliness, uniqueness, etc...  This could be achieved through the usage of deequ but that can be tricker if cross engine execution is envisaged

**Anovos not only supports data quality & EDA metrics but also has interesting modules like data cleaning, data transformation, data stability & drift measurement, feature explorer & recommender (upcoming), integration to feature stores (upcoming), auto ML integration (upcoming). But we will definitely explore deeper into Apache Griffin and see what we are missing w.r.t. to Anovos' current functionalities.** 

> 3. for features engineering, what do you of tools like [featuretools](https://featuretools.alteryx.com/en/stable/) from alteryx?

 **Alteryx featuretool "DeepFeatureSynthesis" supports only non-scalable feature engineering with minimal transformation in place. We have added a 360-degree view of all possible transformations for numerical & categorical variables. Anovos also provides a compelling visualization layer to visualize the data insights. You can look at our reporting capabilities [here](https://docs.anovos.ai/using-anovos/data-reports/html_report.html). Since we do handle massive datasets in our day to day operations, we designed this tool internally to serve that purpose and recently open-sourced them**.

> In both cases, the project looks very promising and it will be interested to see how to contribute to anovos.

**Thank you. You can look at the ways you can contribute to Anovos [here](https://docs.anovos.ai/community/contributing.html). Further, you can look at our road map [here](https://docs.anovos.ai/using-anovos/roadmap.html) and pick up some modules of your interest to have an integration with Anovos.  Feel free to comment with your thoughts.**

**Comment by ziedbouf** [comment]
@kajanansangar thanks for your feedback, looking forward to contribute to anovos, needs to play with the code and grap few features out there. Some other questions please:

1. for the codebase structure, is it inspired from the (pyspark-boilerplate)[https://github.com/mehd-io/pyspark-boilerplate-mehdio]
2. what do you think of adding flask to the table to create something like anovos controller plane? 
3. What do you of spark job submission through livy instead?

**Comment by kajanansangar** [comment]
@ziedbouf **please see my answers inline**

> @kajanansangar thanks for your feedback, looking forward to contribute to anovos, needs to play with the code and grap few features out there. Some other questions please:
> 
> 1. for the codebase structure, is it inspired from the (pyspark-boilerplate)[https://github.com/mehd-io/pyspark-boilerplate-mehdio]
**Codebase structure is based on our internal standards and good to see the above suggestion aligns with ours too.**
> 2. what do you think of adding flask to the table to create something like anovos controller plane?
 **We need more clarification on this. You may write up a small document & share it with us?**
> 3. What do you of spark job submission through livy instead?
**We use Apache-Livy to trigger some of our production jobs which are integrated with some of the Anovos functionalities.**

**Comment by ionicsolutions** [comment]
Hi @ziedbouf, I'm working with the team on turning Anovos into a contributor-friendly and easy-to-maintain open source library.

I saw your comment on PR #59 and would love to get your input on PR #60 regarding code formatting, naming conventions etc.

**Comment by ziedbouf** [comment]
Hi @ionicsolutions,  thanks for referencing the PR. Will look into it in the next few days because i have limited access to internet, And will be happy to contribute. Also i think it will be interesting to add precommit formatting script to the project to automate many format rules.

**Comment by kajanansangar** [comment]
@ziedbouf closing this issue for now since it is not an issue with Anovos. Please feel free to reach us at #oss-anovos channel under MLOPs community slack channel https://mlops-community.slack.com/home

**Comment by ziedbouf** [comment]
Thanks @kajanansangar, please could you let me know how to subscribe to slack channel

**Comment by kajanansangar** [comment]
> Thanks @kajanansangar, please could you let me know how to subscribe to the slack channel

I guess you have already joined there too. Thank you @ziedbouf
